USE "trsis";
CREATE TABLE IF NOT EXISTS clientes ( "id" INTEGER PRIMARY KEY autoincrement, "razon_social" TEXT NOT NULL, "nombre" TEXT NOT NULL, "apellido" TEXT DEFAULT null, "calle" TEXT DEFAULT null, "numero" INTEGER DEFAULT null, "piso" INTEGER DEFAULT null,"depto" INTEGER DEFAULT null,"ciudad" TEXT DEFAULT null,"codigo_postal" TEXT DEFAULT null, "provincia" INTEGER DEFAULT null,"pais" INTEGER DEFAULT null,"tel_fijo" TEXT DEFAULT null,"tel_celular" TEXT DEFAULT null,"fax" TEXT DEFAULT null,"email" TEXT DEFAULT null, "comprobante_email" INTEGER DEFAULT 1, "CUIT/CUIL" TEXT DEFAULT null, "id_estado_fiscal" INTEGER DEFAULT NULL );
INSERT OR UPDATE INTO `clientes` (`id`, `razon_social`, `nombre`, `comprobante_email` ) VALUES ( 0, 'Consumidor Final','Consumidor Final', 1 );
CREATE TABLE IF NOT EXISTS estado_fiscal ( "id_estado_fiscal" INTEGER PRIMARY KEY autoincrement, "titulo" TEXT NOT NULL );
INSERT OR UPDATE INTO `estado_fiscal` (`id_estado_fiscal`, `titulo`) VALUES (1, 'Responsable Inscripto');
INSERT OR UPDATE INTO `estado_fiscal` (`id_estado_fiscal`, `titulo`) VALUES (2, 'Responsable Monotributista');
INSERT OR UPDATE INTO `estado_fiscal` (`id_estado_fiscal`, `titulo`) VALUES (3, 'No Responable Inscripto');
INSERT OR UPDATE INTO `estado_fiscal` (`id_estado_fiscal`, `titulo`) VALUES (4, 'Exento');
INSERT OR UPDATE INTO `estado_fiscal` (`id_estado_fiscal`, `titulo`) VALUES (5, 'Consumidor Final');
INSERT OR UPDATE INTO `estado_fiscal` (`id_estado_fiscal`, `titulo`) VALUES (6, 'Monotributista Social');
INSERT OR UPDATE INTO `estado_fiscal` (`id_estado_fiscal`, `titulo`) VALUES (7, 'Pequeño Contribuidor Eventual');
INSERT OR UPDATE INTO `estado_fiscal` (`id_estado_fiscal`, `titulo`) VALUES (8, 'Pequeño Contribuyente Eventual Social');
CREATE TABLE IF NOT EXISTS paises ( "id_pais" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL , "nombre" TEXT NOT NULL );
INSERT OR UPDATE INTO `paises` VALUES (13, 'Argentina');
CREATE TABLE IF NOT EXISTS provincias ( "id_provincia" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "nombre" TEXT NOT NULL , "id_pais" INTEGER NOT NULL );
INSERT OR UPDATE INTO `provincias` VALUES ( 168, 'Buenos Aires',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 169, 'Catamarca',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 170, 'Chaco',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 171, 'Chubut',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 172, 'Cordoba',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 173, 'Corrientes',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 174, 'Distrito Federal',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 175, 'Entre Rios',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 176, 'Formosa',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 177, 'Jujuy',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 178, 'La Pampa',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 179, 'La Rioja',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 180, 'Mendoza',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 181, 'Misiones',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 182, 'Neuquen',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 183, 'Rio Negro',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 184, 'Salta',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 185, 'San Juan',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 186, 'San Luis',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 187, 'Santa Cruz',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 188, 'Santa Fe',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 189, 'Santiago del Estero',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 190, 'Tierra del Fuego',  13 );
INSERT OR UPDATE INTO `provincias` VALUES ( 191, 'Tucuman',  13 );
CREATE TABLE IF NOT EXISTS "servicios" ("id_servicio" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "nombre" TEXT NOT NULL , "descripcion" TEXT, "fecha_alta" DATETIME NOT NULL , "fecha_baja" DATETIME, "precio_base" DOUBLE NOT NULL , "periodo" INTEGER NOT NULL , "dia_cobro" INTEGER NOT NULL , "forma_incompleto" INTEGER NOT NULL );
CREATE TABLE IF NOT EXISTS "periodo_servicio" ("id_periodo_servicio" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL , "id_servicio" INTEGER NOT NULL , "periodo" INTEGER NOT NULL , "ano" INTEGER NOT NULL , "fecha" DATETIME NOT NULL , "fecha_inicio" DATETIME NOT NULL , "fecha_fin" DATETIME NOT NULL );
CREATE TABLE IF NOT EXISTS "cobro_servicio_cliente_periodo" ("id_periodo_servicio" INTEGER NOT NULL , "id_servicio" INTEGER NOT NULL , "id_cliente" INTEGER NOT NULL , "id_factura" INTEGER NOT NULL , "id_recibo" INTEGER, "id_ctacte" INTEGER, PRIMARY KEY ("id_periodo_servicio", "id_servicio", "id_cliente"));